version: "3"

services:
  vote_api:
    image: vote_api
    build: 
      context: .
    ports:
      - "80:80"
  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/data/db"
    restart: always
    networks:
      - default
  pg_data:
    driver: local