// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/taroxii/vote-api/pkg/entity"
)

// ItemUseCase is an autogenerated mock type for the ItemUseCase type
type ItemUseCase struct {
	mock.Mock
}

// ClearVote provides a mock function with given fields: c, id
func (_m *ItemUseCase) ClearVote(c context.Context, id int64) (entity.Item, error) {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for ClearVote")
	}

	var r0 entity.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (entity.Item, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) entity.Item); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Get(0).(entity.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: c, id
func (_m *ItemUseCase) Delete(c context.Context, id int64) error {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c, cursor, num
func (_m *ItemUseCase) Fetch(c context.Context, cursor string, num int64) ([]entity.Item, string, error) {
	ret := _m.Called(c, cursor, num)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []entity.Item
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]entity.Item, string, error)); ok {
		return rf(c, cursor, num)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []entity.Item); ok {
		r0 = rf(c, cursor, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) string); ok {
		r1 = rf(c, cursor, num)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64) error); ok {
		r2 = rf(c, cursor, num)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Insert provides a mock function with given fields: c, d
func (_m *ItemUseCase) Insert(c context.Context, d *entity.Item) error {
	ret := _m.Called(c, d)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Item) error); ok {
		r0 = rf(c, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: c, d
func (_m *ItemUseCase) Update(c context.Context, d *entity.Item) error {
	ret := _m.Called(c, d)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Item) error); ok {
		r0 = rf(c, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Vote provides a mock function with given fields: c, id, user_id
func (_m *ItemUseCase) Vote(c context.Context, id int64, user_id int64) (*entity.Item, error) {
	ret := _m.Called(c, id, user_id)

	if len(ret) == 0 {
		panic("no return value specified for Vote")
	}

	var r0 *entity.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entity.Item, error)); ok {
		return rf(c, id, user_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entity.Item); ok {
		r0 = rf(c, id, user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(c, id, user_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewItemUseCase creates a new instance of ItemUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemUseCase {
	mock := &ItemUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
